version: "3"
services:
#  java_api:
#    container_name: java_api
#    image: midejoe/java-api:2.0
#    ports:
#      - 8080:8080
#  environment:
#    - DATABASE_URL =
  postgres:
    container_name: security
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres: